apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "kafka.broker.name" . }}
    app.kubernetes.io/part-of: kafka
  name: {{ printf "%s-headless" (include "kafka.broker.name" .) }}
  namespace: {{ include "kafka.namespace" . }}
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-kafka-int
      port: {{ .Values.broker.port }}
      protocol: TCP
      targetPort: tcp-kafka-int
  selector:
    app: {{ include "kafka.broker.name" . }}
  sessionAffinity: None
  type: ClusterIP
