apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "kafka.controller.name" . }}
  name: {{ printf "%s-headless" (include "kafka.controller.name" .) }}
  namespace: {{ include "kafka.namespace" . }}
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-controller
      port: {{ .Values.controller.port }}
      protocol: TCP
      targetPort: tcp-controller
  selector:
    app: {{ include "kafka.controller.name" . }}
  sessionAffinity: None
  type: ClusterIP
